<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Learn more_ie0N9b</name>
   <tag></tag>
   <elementGuidId>0aff272d-2af6-490c-981e-2e1410b377ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='widget-zoom-in']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ie0N9b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ded9b83a-c4f3-4a00-88bc-f88739941c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ie0N9b</value>
      <webElementGuid>7f39b7a3-331b-43aa-8dab-15565955c9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-zoom-in&quot;)/div[@class=&quot;ie0N9b&quot;]</value>
      <webElementGuid>9b77ff68-a9e7-4db9-aa3b-5ec100b4c566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='widget-zoom-in']/div</value>
      <webElementGuid>e45f04d2-aa2e-4819-be22-9f5ee1ad1e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button/div</value>
      <webElementGuid>7567c1ba-1255-408e-bae5-74f650033d6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
