<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WOMEN</name>
   <tag></tag>
   <elementGuidId>4cffedc8-fef1-4ab1-91cf-083ebd247aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appContainer']/div/div/header/div[3]/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b69d4c0-3368-4f51-a812-1335105483d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/shop/women</value>
      <webElementGuid>1cec6131-ca60-4912-a787-8598027cfedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>WOMEN</value>
      <webElementGuid>211d9c81-3c8c-4287-a461-8490dc901001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> alignTag</value>
      <webElementGuid>b5381873-b8bf-4319-bd4c-1d0e35c77469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WOMEN</value>
      <webElementGuid>5f528d7a-1eba-442a-9756-a9047a1b2cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appContainer&quot;)/div[@class=&quot;false header-wrapper&quot;]/div[@class=&quot;main-header dodShadow&quot;]/header[1]/div[@class=&quot;header-right&quot;]/div[@class=&quot;menu-newlist&quot;]/ul[@class=&quot;level-first false&quot;]/li[2]/a[@class=&quot;alignTag&quot;]</value>
      <webElementGuid>05ea8f09-c1c2-42d8-882a-6375d7055f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appContainer']/div/div/header/div[3]/div/ul/li[2]/a</value>
      <webElementGuid>3f5bb3ba-b265-469d-baed-153755c1468e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WOMEN')]</value>
      <webElementGuid>fce31f54-5344-46ef-b625-3b255dba5b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A-Z BRANDS'])[1]/following::a[1]</value>
      <webElementGuid>09c20908-f2ac-43f9-bdd3-8fedbab16ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Woodland'])[2]/following::a[2]</value>
      <webElementGuid>9de98b45-4e52-44c6-aad8-98e07924d0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by:'])[2]/preceding::a[1]</value>
      <webElementGuid>534ec8c4-cee9-442f-80ff-39674b1f7c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORIES'])[2]/preceding::a[1]</value>
      <webElementGuid>ce588ac8-1ee9-4c34-a9a9-9fe349a1d1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WOMEN']/parent::*</value>
      <webElementGuid>85d7bb91-725d-4615-b26b-9c4cf52838fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/shop/women')]</value>
      <webElementGuid>d3998e20-ef14-4647-be8f-49dd9fea0ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[2]/a</value>
      <webElementGuid>468beb0f-1b59-4b3c-98d6-0373c5bd96c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/shop/women' and @title = 'WOMEN' and (text() = 'WOMEN' or . = 'WOMEN')]</value>
      <webElementGuid>e939a9a6-0bf1-48de-89ef-5f8fa22e8cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
