<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MEN</name>
   <tag></tag>
   <elementGuidId>7e207d3d-2f5a-40a3-ae73-841aa5b39c9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='appContainer']/div/div/header/div[3]/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fbc16d5-2f59-4a48-b854-921052cfbb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/shop/men</value>
      <webElementGuid>dc65d2a5-267c-4c6a-adce-920fdb3701a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MEN</value>
      <webElementGuid>30f0eebd-5e26-478f-acae-70a676bc03e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> alignTag</value>
      <webElementGuid>c16bfb3c-b4f6-4eef-8a53-066f92ddbfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MEN</value>
      <webElementGuid>967df222-8d91-4dca-a27a-ff83b3538d33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appContainer&quot;)/div[@class=&quot;false header-wrapper&quot;]/div[@class=&quot;main-header dodShadow&quot;]/header[1]/div[@class=&quot;header-right&quot;]/div[@class=&quot;menu-newlist&quot;]/ul[@class=&quot;level-first false&quot;]/li[1]/a[@class=&quot;alignTag&quot;]</value>
      <webElementGuid>43667aaf-03e2-48bd-bb3f-fa85313c0a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appContainer']/div/div/header/div[3]/div/ul/li/a</value>
      <webElementGuid>7499f8b2-65a5-4b98-b571-61290fc8e614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MEN')]</value>
      <webElementGuid>ba9d9b06-b7f9-49e8-b8a9-32c505ef5dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit AJIOLUXE'])[1]/following::a[2]</value>
      <webElementGuid>0ebd62fd-9a4d-4f00-a8b8-527bd2cf51d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Care'])[1]/following::a[3]</value>
      <webElementGuid>4d23e070-85ec-4429-9f64-13b1541a46b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by:'])[1]/preceding::a[1]</value>
      <webElementGuid>eee18789-3b44-423f-b8e7-b2c3c65b781b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CATEGORIES'])[1]/preceding::a[1]</value>
      <webElementGuid>bedcec63-2979-42ea-8ca4-9d5bbcad3397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MEN']/parent::*</value>
      <webElementGuid>5c7769fb-1735-4eb2-9065-78c2af8a75ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/shop/men')]</value>
      <webElementGuid>3c814ef6-8d44-4de3-8920-01f912f676d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a</value>
      <webElementGuid>87245430-6558-4569-bac7-97702355b3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/shop/men' and @title = 'MEN' and (text() = 'MEN' or . = 'MEN')]</value>
      <webElementGuid>5848f69f-ebf5-4ddf-aab8-24163c3adabc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
