<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign In  Join AJIO_ic-close-quickview</name>
   <tag></tag>
   <elementGuidId>afdc6f57-933f-4a3b-8d3f-c3b97e6abfc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-modal']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ic-close-quickview</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52b4a001-2526-4bb9-aaed-cc21995d9d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic-close-quickview</value>
      <webElementGuid>fe7737b7-c385-4bab-9530-756f149dc8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-modal&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ic-close-quickview&quot;]</value>
      <webElementGuid>b7c5b3ef-cf7c-4343-a85c-71a4ec7b80f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-modal']/div/div/div</value>
      <webElementGuid>66c0820c-8e77-4189-996e-87da6fca6095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/div/div/div</value>
      <webElementGuid>a935550f-c2db-4e1f-87cc-9e01485fb337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
