<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country_autosuggest</name>
   <tag></tag>
   <elementGuidId>24a85057-7c35-4dab-ba2b-0ba3a0416ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#autosuggest</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='autosuggest']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffa120cf-6a57-4fe6-96c5-12a59a7a6dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e0f443b-3d11-4067-8a1f-b52cfd5a63e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>autosuggest</value>
      <webElementGuid>2226d740-93f9-4ed5-80d9-15c9cac403d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputs ui-autocomplete-input</value>
      <webElementGuid>4a1e5be7-7dd5-42af-96fb-43954261ff92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type to Select</value>
      <webElementGuid>8f4686f1-6e5a-442b-b21c-cced070b5a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>90a7cc7f-6058-40f1-b138-082e19ee6506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autosuggest&quot;)</value>
      <webElementGuid>4e237edc-6a15-4836-b19d-d6cc8b10f3c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='autosuggest']</value>
      <webElementGuid>743600eb-e60b-4d1d-9836-9459dda34100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='select-class-example']/fieldset/input</value>
      <webElementGuid>7fa094ac-c832-4916-9768-064e2e84f9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>81c0f452-b6c5-47c4-b799-97c9b6dd2b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'autosuggest' and @placeholder = 'Type to Select']</value>
      <webElementGuid>1c37028e-2abd-4abc-a0ce-a5b99485ae75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
