<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wed, Jul 12 2023_ctl00mainContentchk__47242d</name>
   <tag></tag>
   <elementGuidId>0c98372e-2e63-449d-88b1-b45db235ab17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_mainContent_chk_friendsandfamily</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_mainContent_chk_friendsandfamily']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f4e6ef7-ef70-4d15-904b-c9cc44b6b73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_mainContent_chk_friendsandfamily</value>
      <webElementGuid>7fd9f7f6-b562-462a-8fe4-ac39570b8e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>55809029-6561-4bc1-9c1b-f6c1eda12ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$mainContent$chk_friendsandfamily</value>
      <webElementGuid>8886448b-d49d-400e-97bf-a19e59698ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_chk_friendsandfamily&quot;)</value>
      <webElementGuid>a5896b53-8294-426d-bb7a-dd02df8e58a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_mainContent_chk_friendsandfamily']</value>
      <webElementGuid>53403e4c-99fc-46b7-b2d7-f81ced21edab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='familyandfriend']/input</value>
      <webElementGuid>735b3c20-955f-414b-a724-7f0b080cd897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/input</value>
      <webElementGuid>0e7309ad-e6be-44dc-8623-5a70f660e923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ctl00_mainContent_chk_friendsandfamily' and @type = 'checkbox' and @name = 'ctl00$mainContent$chk_friendsandfamily']</value>
      <webElementGuid>d19e5894-1a62-4cac-b408-e777fc1eb5c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
