<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Multicity</name>
   <tag></tag>
   <elementGuidId>6c6fcacd-4b6a-4146-b4ae-c5aa9c66768d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(3) > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ctl00_mainContent_rbtnl_Trip']/tbody/tr/td[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4496d3d6-2afa-4b46-83e5-2d4c4b5b12ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ctl00_mainContent_rbtnl_Trip_2</value>
      <webElementGuid>06cda326-265e-4d2a-975c-ba0de60e1a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Multicity</value>
      <webElementGuid>3495e442-d52b-4a85-9f94-46cfe0562a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_rbtnl_Trip&quot;)/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>3477d9f2-55bc-4fd5-a86c-837966b2d04d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ctl00_mainContent_rbtnl_Trip']/tbody/tr/td[3]/label</value>
      <webElementGuid>999e60bc-8760-458f-85bd-30134c49393a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Round Trip'])[1]/following::label[1]</value>
      <webElementGuid>50afbdc7-e288-4977-ae44-6837f2fa9e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One Way'])[1]/following::label[2]</value>
      <webElementGuid>69583bbc-76d1-4121-99e2-e5a32568c712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::label[1]</value>
      <webElementGuid>89e16861-8993-4a52-8de0-2e903e79058a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FROM'])[1]/preceding::label[1]</value>
      <webElementGuid>8e953230-2afc-44ba-a432-cf2cab3dddfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Multicity']/parent::*</value>
      <webElementGuid>915d3a0b-d7f2-476d-875c-736fbb18d527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/label</value>
      <webElementGuid>f4045b1f-d642-4d2a-a4d6-0e9231f3916d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Multicity' or . = 'Multicity')]</value>
      <webElementGuid>b58bc7c4-1afe-43ea-862d-c381934895bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
