<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Hotels</name>
   <tag></tag>
   <elementGuidId>6ecfebe0-3c69-49a9-abd4-4389cd1b15a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Hotels&quot;] > span.text-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttons']/div/div/ul/li[2]/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0be67868-7624-4332-ab25-7a82acb146f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-label</value>
      <webElementGuid>c6e2f4eb-ff76-4732-8879-48e853566830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hotels
                                        </value>
      <webElementGuid>312c7932-f81b-4c2d-a5ad-62bae2041ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttons&quot;)/div[@class=&quot;search-buttons-heading&quot;]/div[@class=&quot;button-align-center&quot;]/ul[1]/li[@class=&quot;myspice_trip&quot;]/a[1]/span[@class=&quot;text-label&quot;]</value>
      <webElementGuid>3f46db5a-068b-431b-a747-7dc1c460448b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buttons']/div/div/ul/li[2]/a/span[2]</value>
      <webElementGuid>608fc2c9-a8c7-4fbd-a13b-19e4bb266560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::span[2]</value>
      <webElementGuid>cef4ffd8-b7f5-47ea-b543-b2dd4a85d98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='.'])[3]/following::span[4]</value>
      <webElementGuid>7f869e2e-7390-4aac-81ea-0b190d8b3470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Holiday Packages'])[1]/preceding::span[2]</value>
      <webElementGuid>38f65786-d6ac-4847-8973-7a78d5ad0074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Status'])[3]/preceding::span[4]</value>
      <webElementGuid>a573b16b-34b3-4b51-a461-6c7a3d7db14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hotels']/parent::*</value>
      <webElementGuid>eedbe482-30ba-4a71-997e-4be45cd8ec4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/ul/li[2]/a/span[2]</value>
      <webElementGuid>56cbb92b-29e2-4d2d-a3a4-d5f053499d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Hotels
                                        ' or . = 'Hotels
                                        ')]</value>
      <webElementGuid>0421cf30-c41b-4825-b147-36a4e3756638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
