<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Images</name>
   <tag></tag>
   <elementGuidId>43b47ad5-234e-48c6-93b2-f0b8c1939274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.O3S9Rb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cnt']/div[5]/div/div/div/div/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25da0092-5894-4a5f-b84d-9e6bd63d890f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>O3S9Rb</value>
      <webElementGuid>42dcf25a-9842-40ad-919b-be3545493ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Images</value>
      <webElementGuid>b1c4ddd8-9c56-4f87-a381-d861c4c16ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cnt&quot;)/div[@class=&quot;rfiSsc&quot;]/div[@class=&quot;sBbkle&quot;]/div[@class=&quot;aAbqZ&quot;]/div[@class=&quot;xhjkHe&quot;]/div[@class=&quot;TrmO7&quot;]/div[@class=&quot;nfdoRb&quot;]/a[@class=&quot;zItAnd FOU1zf&quot;]/div[@class=&quot;O3S9Rb&quot;]</value>
      <webElementGuid>32bab617-e59e-4b08-86fe-9c0921c1a4ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cnt']/div[5]/div/div/div/div/div/a/div</value>
      <webElementGuid>2e627fac-b0a5-4af4-916d-dd1849424323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters and topics'])[2]/following::div[1]</value>
      <webElementGuid>4dc13831-2572-433b-9c14-f457b380abd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters and topics'])[1]/following::div[9]</value>
      <webElementGuid>921f5974-c1cd-4fa5-9cfc-cab55d15f825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salary'])[1]/preceding::div[1]</value>
      <webElementGuid>60cecf06-8710-4115-8de6-963de79521e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs'])[1]/preceding::div[2]</value>
      <webElementGuid>4b67f62d-5f4e-4698-be7e-211ed40313d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Images']/parent::*</value>
      <webElementGuid>f4dc568f-7df9-4119-85a8-f04b953d92c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>34a93a34-02ca-4a07-8c30-910e6a2d89bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Images' or . = 'Images')]</value>
      <webElementGuid>4993b2ca-2a1f-4576-99f1-31b2977c5bc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
