<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-icon_Back_guide-icon</name>
   <tag></tag>
   <elementGuidId>0a9b72ca-74a3-482f-bac8-245d1387bb2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#guide-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//yt-icon[@id='guide-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-icon</value>
      <webElementGuid>b79bc029-ada9-40d3-8e98-d0ddc21806a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guide-icon</value>
      <webElementGuid>cee651bd-1e0f-4eff-8c70-79d9defd28c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>yt-icons:menu</value>
      <webElementGuid>d8c6afa5-03e5-4aff-bd04-304f735bbe8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope ytd-masthead</value>
      <webElementGuid>1ca4e009-d0e1-4abb-8f9b-97ecf477d1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start&quot;)/yt-icon-button[@id=&quot;guide-button&quot;]/button[@id=&quot;button&quot;]/yt-icon[@id=&quot;guide-icon&quot;]</value>
      <webElementGuid>40645012-3e41-4ee0-b288-f90d95bd3639</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//yt-icon[@id='guide-icon']</value>
      <webElementGuid>fc62003b-3ada-49cf-9137-5781c655ef94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//button[@id='button']/yt-icon)[5]</value>
      <webElementGuid>1ed6f241-2669-414b-bf7c-174f75fd62c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::yt-icon[1]</value>
      <webElementGuid>7c010814-1a0b-4e85-bae8-f093e46cb739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NaN / NaN'])[1]/following::yt-icon[3]</value>
      <webElementGuid>caed9595-c173-4e02-990f-40402d185f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IN'])[1]/preceding::yt-icon[3]</value>
      <webElementGuid>d7fa7a19-87f4-41e6-8f97-67a4a333dd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip navigation'])[1]/preceding::yt-icon[3]</value>
      <webElementGuid>4da1717b-455b-4865-a230-bcddbc21037d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//yt-icon-button[2]/button/yt-icon</value>
      <webElementGuid>2787d9dc-e771-40f9-904f-71eebdb00b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-icon[@id = 'guide-icon']</value>
      <webElementGuid>da7e1a7f-c8ca-4306-b670-58ab6c7463bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
